Enchacement/fef 64/db connection
facom-em-foco/backend pull request #1
Opened 2024-09-10 22:43 UTC by joaoPedro-OliveiraFigueiredo

2024-09-10 22:55 UTC, EduardoSLuz requested changes

2024-09-10 22:55 UTC, EduardoSLuz commented on docker-compose.yml
Seria interessante mover as credenciais do banco de dados para o arquivo de variáveis de ambiente (Environments) , utilizando as variáveis apenas como referência no docker-compose. Depois, inclua essas variáveis no arquivo .env.example para documentar sua existência.

2024-09-10 23:13 UTC, joaoPedro-OliveiraFigueiredo commented on docker-compose.yml
alterado

2024-09-10 23:33 UTC, MashiroK approved these changes

2024-09-11 00:28 UTC, EduardoSLuz approved these changes
Muito bom 🚀

2024-09-11 00:38 UTC, merged