feat : get user and publishers by id
facom-em-foco/backend pull request #14
Opened 2024-10-31 00:55 UTC by joaoPedro-OliveiraFigueiredo

2024-10-31 22:47 UTC, MashiroK approved these changes

2024-10-31 23:21 UTC, EduardoSLuz commented on src/parsers/user.parser.ts
> +    totalPosts: 0,
porque para publicador o total de post retorna 0 e para user retorna a quantidade salva no banco, não seria ao contrário? já que é o publicador que vai postar os avisos (noticias)

2024-10-31 23:24 UTC, EduardoSLuz requested changes
ajustar código

2024-11-04 20:59 UTC, EduardoSLuz approved these changes
OK 👍

2024-11-04 21:00 UTC, merged